### ISSUE TITLE
Too many value to unpack bug 

### ISSUE THREAD

**Issue by JD-ETH** [MIT-TESSE/tesse-gym#5]
happens when running the training. 
```
Traceback (most recent call last):
  File "/home/jd/anaconda3/envs/goseek/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/jd/anaconda3/envs/goseek/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jd/anaconda3/envs/goseek/lib/python3.7/site-packages/stable_baselines/common/vec_env/subproc_vec_env.py", line 18, in _worker
    observation, reward, done, info = env.step(data)
  File "/home/jd/anaconda3/envs/goseek/lib/python3.7/site-packages/tesse_gym-0.1.4-py3.7.egg/tesse_gym/core/tesse_gym.py", line 214, in step
    return self.form_agent_observation(response), reward, self.done, reward_info
  File "/home/jd/anaconda3/envs/goseek/lib/python3.7/site-packages/tesse_gym-0.1.4-py3.7.egg/tesse_gym/tasks/goseek/goseek_full_perception.py", line 69, in form_agent_observation
    eo, seg, depth = tesse_data.images
ValueError: too many values to unpack (expected 3)

```

**Comment by JD-ETH** [comment]
This may have to do with me turning off the screen. I couldn't observe it now again when I'm traning with active rendering on screen.
